#!/bin/bash

S="$HOME/.runluascript.lua"

vim $S
printf "Should I run Lua script? [Y/n]: "
read R
if test "$R" = "y" || \
	test "$R" = "Y"  || \
	test "$R" = "" 
then
	lua $S
	exit $?
else
	exit 0
fi

